"use client";
import { FormEvent, useState } from "react"; import { useRouter } from "next/navigation";
import { Shell, SectionTitle, Status } from "@/components/shell"; import { useDemo } from "@/components/workspace-context";
import { CalendarDaysIcon, ShieldCheckIcon } from "@/components/icons"; import { ArrowRightIcon, CheckCircleIcon, ClockIcon, UserPlusIcon } from "@heroicons/react/24/outline";

export default function Reception(){const {patient,savePatient}=useDemo();const router=useRouter();const [form,setForm]=useState(patient);const [created,setCreated]=useState(false);const change=(k:string,v:string)=>setForm({...form,[k]:v});const submit=(e:FormEvent)=>{e.preventDefault();savePatient({...form,status:"Ready for nurse"});setCreated(true)};
 return <Shell title="Reception desk" eyebrow="Patient intake"><div className="mb-7 flex flex-col justify-between gap-4 md:flex-row md:items-end"><SectionTitle eyebrow="Today · September 23" title="Welcome back, Alex" description="Register patients and coordinate today’s intake flow."/><div className="flex gap-3"><div className="card px-4 py-3"><p className="text-[10px] font-bold uppercase tracking-wider text-muted">Waiting</p><p className="mt-1 text-xl font-extrabold">03</p></div><div className="card px-4 py-3"><p className="text-[10px] font-bold uppercase tracking-wider text-muted">Seen today</p><p className="mt-1 text-xl font-extrabold">12</p></div></div></div>
 <div className="grid gap-6 xl:grid-cols-[1fr_360px]"><form onSubmit={submit} className="card overflow-hidden"><div className="flex items-center justify-between border-b border-line p-6"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-teal-50 text-teal-700"><UserPlusIcon className="h-5 w-5"/></span><SectionTitle title="New patient intake" description="Enter the patient’s visit and contact details."/></div><Status tone="slate">Draft</Status></div><div className="grid gap-5 p-6 md:grid-cols-2"><Field label="Full name"><input className="input" value={form.name} onChange={e=>change("name",e.target.value)} required/></Field><Field label="Date of birth"><input type="date" className="input" value={form.dob} onChange={e=>change("dob",e.target.value)} required/></Field><Field label="Patient ID"><input className="input" value={form.id} onChange={e=>change("id",e.target.value)} required/></Field><Field label="Phone number"><input className="input" value={form.phone} onChange={e=>change("phone",e.target.value)} required/></Field><Field label="Insurance provider"><input className="input" value={form.insurance} onChange={e=>change("insurance",e.target.value)} required/></Field><Field label="Appointment date & time"><input type="datetime-local" className="input" value={form.appointment} onChange={e=>change("appointment",e.target.value)} required/></Field><div className="md:col-span-2"><Field label="Reason for visit"><textarea rows={4} className="input resize-none" value={form.reason} onChange={e=>change("reason",e.target.value)} required/></Field></div></div><div className="flex items-center justify-end border-t border-line bg-canvas/60 px-6 py-4"><button className="btn-primary" type="submit">Create patient <ArrowRightIcon className="h-4 w-4"/></button></div></form>
 <div className="space-y-5">{created?<div className="card overflow-hidden border-teal-100"><div className="bg-teal-700 p-6 text-white"><CheckCircleIcon className="h-8 w-8"/><p className="mt-5 text-[10px] font-bold uppercase tracking-[.16em] text-teal-100">Handoff complete</p><h3 className="mt-2 text-xl font-bold">Patient sent to Nurse</h3><p className="mt-2 text-xs leading-5 text-teal-100">{form.name} is now visible in the nurse workspace with the reception context attached.</p></div><div className="p-5"><button onClick={()=>router.push("/nurse")} className="btn-primary w-full">Continue to Nurse <ArrowRightIcon className="h-4 w-4"/></button></div></div>:<div className="card p-5"><SectionTitle title="Current session" description="No placeholder queue records are shown."/><div className="mt-5 rounded-xl border border-dashed border-line bg-canvas p-5 text-center"><p className="text-sm font-bold">No patient registered yet</p><p className="mt-1 text-xs text-muted">Complete the intake form to begin this workflow.</p></div></div>}
 <div className="card p-5"><div className="flex gap-3"><ShieldCheckIcon className="h-5 w-5 shrink-0 text-teal-600"/><div><p className="text-sm font-bold">Privacy reminder</p><p className="mt-1 text-xs leading-5 text-muted">Confirm identity before discussing or recording visit details.</p></div></div></div></div></div></Shell>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label><span className="label">{label}</span>{children}</label>}
function Queue({initials,name,time,status}:{initials:string;name:string;time:string;status:string}){return <div className="flex items-center gap-3 rounded-xl border border-line p-3"><span className="grid h-9 w-9 place-items-center rounded-full bg-slate-100 text-[10px] font-bold">{initials}</span><div className="min-w-0 flex-1"><p className="truncate text-xs font-bold">{name}</p><p className="mt-0.5 flex items-center gap-1 text-[10px] text-muted"><ClockIcon className="h-3 w-3"/>{time}</p></div><Status tone={status==="Waiting"?"amber":status==="With nurse"?"teal":"blue"}>{status}</Status></div>}
