import { AIResult, AllergyGuidance, ClaimResult, ClinicalRecord, Extraction, PatientSummary, RedFlagAlert, Segment } from "./ai-types";
const base=process.env.NEXT_PUBLIC_API_URL||"/api";
async function request<T>(path:string,init:RequestInit):Promise<T>{const r=await fetch(base+path,init);if(!r.ok){let msg=`Request failed (${r.status})`;try{msg=(await r.json()).detail||msg}catch{}throw new Error(msg)}return r.json()}
export async function transcribeAudio(blob:Blob,role:"nurse"|"doctor",filename="recording.webm"){const form=new FormData();form.append("file",blob,filename);form.append("role",role);return request<AIResult>("/transcribe",{method:"POST",body:form})}
export async function analyzeTranscript(segments:Segment[],role:"nurse"|"doctor"){return request<Omit<AIResult,"segments">>("/extract",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({segments,role})})}
export async function createRecord(reception:Record<string,unknown>,nurse:Segment[],doctor:Segment[]){return request<ClinicalRecord>("/clinical-record",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({reception,nurse,doctor})})}
export async function generateOutputs(record:ClinicalRecord){return request<Record<string,Record<string,unknown>>>("/outputs",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({record})})}
export async function checkClaims(fields:Extraction,segments:Segment[]){return request<{results:Record<string,ClaimResult>}>("/claims-check",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({fields,segments})})}
export async function detectRedFlags(segments:Segment[]){return request<{alerts:RedFlagAlert[]}>("/red-flags",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({segments})})}
export async function generatePatientSummary(record:ClinicalRecord,language:string){return request<PatientSummary>("/patient-summary",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({record,language})})}
export async function allergyGuidance(segments:Segment[],allergies?:string|null,current_medications?:string|null){return request<{guidance:AllergyGuidance[]}>("/allergy-guidance",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({segments,allergies,current_medications})})}
