import { AlignmentType, Document, HeadingLevel, Packer, Paragraph, Table, TableCell, TableRow, TextRun, WidthType } from "docx";
import type { ClinicalRecord } from "./ai-types";
import type { Patient } from "./workspace-data";

export type ReportAudience="insurance"|"pharmacy"|"patient";
type Outputs=Record<string,Record<string,unknown>>;

const value=(record:ClinicalRecord,key:string)=>record.fields[key]?.value?.trim()||"Not documented";
const output=(outputs:Outputs|null,audience:ReportAudience,key:string)=>String(outputs?.[audience]?.[key]||"Not documented");
const filenamePart=(value:string)=>value.replace(/[^a-z0-9]+/gi,"-").replace(/^-|-$/g,"").toLowerCase()||"patient";

export async function downloadWordReport(audience:ReportAudience,patient:Patient,record:ClinicalRecord,outputs:Outputs|null){
  if(record.status!=="clinician_verified")throw new Error("The clinical record must be verified before a report can be created.");
  const title={insurance:"Insurance Clinical Report",pharmacy:"Pharmacy Medication Report",patient:"Patient Visit Report"}[audience];
  const recipient={insurance:"Insurance reviewer",pharmacy:"Dispensing pharmacist",patient:"Patient"}[audience];
  const sections=audience==="insurance"?insuranceSections(record,outputs):audience==="pharmacy"?pharmacySections(record,outputs):patientSections(record,outputs);
  const doc=new Document({styles:{default:{document:{run:{font:"Aptos",size:22,color:"1F2937"},paragraph:{spacing:{after:140,line:300}}}},paragraphStyles:[{id:"Title",name:"Title",basedOn:"Normal",next:"Normal",run:{font:"Aptos Display",size:36,bold:true,color:"000000"},paragraph:{spacing:{after:220}}},{id:"Heading1",name:"Heading 1",basedOn:"Normal",next:"Normal",quickFormat:true,run:{font:"Aptos Display",size:26,bold:true,color:"000000"},paragraph:{spacing:{before:260,after:120},keepNext:true}}]},sections:[{properties:{page:{margin:{top:900,right:900,bottom:900,left:900}}},children:[
    new Paragraph({text:title,heading:HeadingLevel.TITLE}),
    new Paragraph({children:[new TextRun({text:`Prepared for ${recipient}`,bold:true}),new TextRun(" from the clinician-verified encounter record. This report does not add clinical claims beyond the verified documentation.")]}),
    patientTable(patient),
    ...sections.flatMap(section=>[new Paragraph({text:section.heading,heading:HeadingLevel.HEADING_1}),...section.items.map(item=>fieldParagraph(item.label,item.value))]),
    new Paragraph({text:"Verification and use",heading:HeadingLevel.HEADING_1}),
    new Paragraph({text:audience==="pharmacy"?"Dispense only medication explicitly authorized by the treating clinician. If medication, dose, route, frequency, or duration is not documented, contact the prescriber before dispensing.":audience==="insurance"?"This document summarizes verified clinical information. It does not determine coverage, eligibility, coding, or reimbursement.":"This plain-language report summarizes the verified visit record and does not replace instructions from the treating clinician."}),
  ]}]});
  const blob=await Packer.toBlob(doc);
  const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download=`${filenamePart(patient.id||patient.name)}-${audience}-report.docx`;document.body.appendChild(anchor);anchor.click();anchor.remove();URL.revokeObjectURL(url);
}

function patientTable(patient:Patient){const rows=[["Patient",patient.name||"Not documented"],["Patient ID",patient.id||"Not documented"],["Date of birth",patient.dob||"Not documented"],["Appointment",patient.appointment?new Date(patient.appointment).toLocaleString():"Not documented"],["Reason for visit",patient.reason||"Not documented"]];return new Table({width:{size:100,type:WidthType.PERCENTAGE},rows:rows.map(([label,data])=>new TableRow({children:[new TableCell({width:{size:30,type:WidthType.PERCENTAGE},children:[new Paragraph({children:[new TextRun({text:label,bold:true})]})]}),new TableCell({width:{size:70,type:WidthType.PERCENTAGE},children:[new Paragraph(data)]})]}))})}
function fieldParagraph(label:string,data:string){return new Paragraph({children:[new TextRun({text:`${label}: `,bold:true}),new TextRun(data||"Not documented")]})}
function insuranceSections(record:ClinicalRecord,outputs:Outputs|null){return [{heading:"Clinical summary",items:[{label:"Summary",value:output(outputs,"insurance","clinical_summary")},{label:"Chief complaint",value:value(record,"chief_complaint")},{label:"Symptoms",value:value(record,"symptoms")},{label:"Duration",value:value(record,"duration")},{label:"Severity",value:value(record,"severity")}]},{heading:"Objective and clinical information",items:vitals(record).concat([{label:"Examination findings",value:value(record,"examination_findings")},{label:"Clinician documented diagnosis",value:value(record,"diagnosis")},{label:"Treatment",value:value(record,"treatment")},{label:"Follow up",value:value(record,"follow_up_instructions")},{label:"Clinical justification",value:output(outputs,"insurance","clinical_justification")}])}]}
function pharmacySections(record:ClinicalRecord,outputs:Outputs|null){const medication=output(outputs,"pharmacy","medication");return [{heading:"Medication authorization",items:[{label:"Clinician documented medication",value:medication},{label:"Dosage",value:output(outputs,"pharmacy","dosage")},{label:"Frequency",value:output(outputs,"pharmacy","frequency")},{label:"Duration",value:output(outputs,"pharmacy","duration")},{label:"Instructions",value:output(outputs,"pharmacy","instructions")}]},{heading:"Medication safety",items:[{label:"Documented allergies",value:value(record,"allergies")},{label:"Current medications",value:value(record,"current_medications")},{label:"Important notes",value:value(record,"important_notes")}]}]}
function patientSections(record:ClinicalRecord,outputs:Outputs|null){const combined=Object.values(record.fields).map(field=>field.value||"").join(" ");const leave=/\b(sick leave|medical leave|time off work|work note|fit note|absence from work)\b/i.test(combined)?combined.match(/[^.]*\b(?:sick leave|medical leave|time off work|work note|fit note|absence from work)\b[^.]*/i)?.[0]?.trim()||"Mentioned in the verified record":"Not documented";return [{heading:"How you reported feeling",items:[{label:"Main concern",value:value(record,"chief_complaint")},{label:"Symptoms",value:value(record,"symptoms")},{label:"Duration",value:value(record,"duration")},{label:"How it affected you",value:value(record,"severity")}]},{heading:"Visit information",items:[{label:"What the clinician documented",value:output(outputs,"patient","clinician_documented")},{label:"Medication instructions",value:output(outputs,"patient","medication_instructions")},{label:"Follow up and warnings",value:output(outputs,"patient","follow_up")},{label:"Sick leave or work note",value:leave},{label:"Important notes",value:value(record,"important_notes")}]}]}
function vitals(record:ClinicalRecord){return [{label:"Temperature",value:value(record,"temperature")},{label:"Blood pressure",value:value(record,"blood_pressure")},{label:"Heart rate",value:value(record,"heart_rate")},{label:"Respiratory rate",value:value(record,"respiratory_rate")},{label:"Oxygen saturation",value:value(record,"oxygen_saturation")},{label:"Weight",value:value(record,"weight")}]}
